### ISSUE TITLE
potential data races in RouteselectActivity.java

### ISSUE THREAD

**Issue by yulin2** [gdmalet/grtransit#10]
Dear developers of grtransit,

I'm a Ph.D. student and I'm doing research on checking data races for Android apps. I found there is a data race in RouteselectActivity.java:

At line 158, the cursor "mCsr" is written in the AsyncTask (and this is the only written for "mCsr"). However, "mCsr" is read by "onListItemClick" at line 59 and 60. The order of the written and read is not guaranteed: after the "onCreate()" finishes, user may touch the items on the screen (i.e., "onListItemClick()" is invoked) and "mCsr" is read. But at this time point, the line 158 in AsyncTask may not be executed or not finish yet, because of the non-deterministic of concurrency. If so, there will be a NullPointerException at line 59.

A quick fix can be add a null checking before line 59:
if(mCsr == null) return;

A more complex fix would be using wait/notify, or latch.

What do you think?

Thanks,
Yu

**Comment by burcuku** [comment]
Hi,

I am a PhD student working on concurrency in Android apps. While examining the potential race Yulin has pointed out, I realized that the accesses to mCsr are implicitly ordered and do not result in a real race.

onListItemClick can be triggered only after the list adapter is set and the items are visible. The list adapter is set in onPostExecute method, after the completion of the task in doInBackground. Hence, mCsr is already set when onListItemClick is executed.

I would like to get your comments on this issue.

Thanks in advance.

**Comment by gdmalet** [comment]
@burcuku, thanks for the comments! I'm going to be working on the code in the next few days, and will study what you said and give a proper answer. I'm working on something else at the moment and don't want to be distracted :-)

**Comment by gdmalet** [comment]
@burcuku  I think @yulin2 was looking at a version of the code closer to https://github.com/gdmalet/grtransit/blob/871ca639ed547efbf85f821811a3bfb43c08816e/Android/app/src/main/java/net/kw/shrdlu/grtgtfs/Activities/RouteselectActivity.java .

The line numbers don't quite match up to his comments, but lines 73 and 74 do indeed use mCsr. However, I agree with your comments that the touch-listener is not set until after mCsr is set (line 206 in that version), so I don't think there is or was a problem.

This was fixed in changed anyhow in commit 11be11851f876198745edb707eb9c811893da48f -- see
https://github.com/gdmalet/grtransit/blob/11be11851f876198745edb707eb9c811893da48f/Android/app/src/main/java/net/kw/shrdlu/grtgtfs/Activities/RouteselectActivity.java . In that version in line 78 and on the values that were stored in the textView are read instead, which is much safer, as it doesn't need the cursor at all.

I'm going to close this issue as I think we agree there is no problem. Many thanks for your input though! I appreciate people taking the time to check my work, although I must admit I work on this app in irregular bursts so can be slow to respond, so apologize for that. 

g
